### POST /users/register
POST http://localhost:8000/api/users/register
Content-Type: application/json

{
  "name": "test_user",
  "email": "test@mail.com",
  "password": "mypassword"
}

### POST /users/login
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
  "email": "test@mail.com",
  "password": "mypassword"
}
> {% client.global.set("auth_token", response.body.data.jwt); %}

### GET /users/info
GET http://localhost:8000/api/users/info
Authorization: Bearer {{auth_token}}
